name: External Actions

on: [push]

jobs:
  run-external-action:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world javascript
        id: hw
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Mauro
      - name: Log output
        run: echo {{ steps.hw.outputs.time }}
